language: php

php:
  - 5.6
  - 7
  - hhvm

branches:
  only:
      - master
      - develop

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - wget https://phar.phpunit.de/phpunit.phar

script: php phpunit.phar --coverage-clover build/logs/clover.xml

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v --exclude-no-stmt; fi;'
