language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
      - master
      - develop

before_script:
  - composer install --no-interaction --prefer-source
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then bin/coveralls -v; fi;'

script: bin/phpunit -c app --coverage-clover build/logs/clover.xml
