language: php

php:
  - 5.6
  - 7
  - hhvm

branches:
  only:
      - master
      - develop

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script: php bin/phpunit --coverage-php build/logs/coverage.cov

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
