language: php

php:
  - 7
  - 7.1

branches:
  only:
      - master
      - develop

before_script:
  - composer self-update
  - mkdir var/jwt
  - openssl genrsa -passout pass:passphrase -out var/jwt/private.pem -aes256 4096
  - openssl rsa -passin pass:passphrase -pubout -in var/jwt/private.pem -out var/jwt/public.pem
  - composer install --no-interaction --prefer-source
  - wget https://phar.phpunit.de/phpunit.phar

script: php phpunit.phar --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt
