security:
    encoders:
        BlogBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_API]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db:
            id: uecode.api_key.provider.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/tokens
            anonymous: true
        secured:
            pattern: ^/
            methods: [POST, PUT, PATCH, DELETE]
            api_key: true
            stateless: true
            provider: db
        main:
            pattern: ^/
            anonymous: true

    access_control:
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
