security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_API]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            methods: [POST, PUT, PATCH, DELETE]
            form_login: false
            provider: fos_userbundle
            http_basic:
                realm: "Secured area"
            anonymous: true

    access_control:
        - { path: ^/article, roles: ROLE_API, methods: [POST, PUT, PATCH, DELETE] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
