# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: BlogBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    post_handler:
        class: BlogBundle\Handler\PostHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - BlogBundle\Entity\Post
            - "@form.factory"
